---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cakephp-ex
spec:
  output:
    to:
      kind: DockerImage
      name: "registry.natwest.gitlab-dedicated.com/natwestgroup/digitalx/technology/hostingsolutions/sharedplatformsandobservability/private-cloud-sandbox/cakephp-example/cakephp-pcs-image:{{ namespace.name }}"
    pushSecret:
      name: github-pcs-reg-token
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi9/php-81@sha256:170dcac5aa35810b941e18d73a45be69201d430ac54b5ac9b4d84f57dc68d6ed'
  source:
    type: Git
    git:
      uri: 'https://github.com/GagandeepMal/cakephp-ex'
    contextDir: /
    sourceSecret:
      name: github-pcs-token
  triggers:
    - type: ConfigChange
  runPolicy: Serial