---
apiVersion: v1
kind: Secret
metadata:
  name: github-pcs-token
data:
  password: "{{ github_pcs_token_pass | b64encode }}"
  username: "{{ github_pcs_token_user | b64encode }}"
type: kubernetes.io/basic-auth