---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pcs-token
data:
  password: "{{ gitlab_pcs_token_pass | b64encode }}"
  username: "{{ gitlab_pcs_token_user | b64encode }}"
type: kubernetes.io/basic-auth